name: Clone File to Another Repo

on:
  push:
    branches: [main]
    paths:
      - 'all_metadata.json'
  workflow_dispatch:

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: source-repo

    - name: Checkout destination repository
      uses: actions/checkout@v4
      with:
        repository: 'DLakesummer/dlakesummer.github.io'
        token: ${{ secrets.DEST_PAT }}
        path: dest-repo

    - name: Copy file(s)
      run: |
        cp data_lake/all_metadata.json \
           dlakesummer.github.io/docs/assets/js/

    - name: Commit & push changes to destination
      run: |
        cd dest-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add .

        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        git commit -m "Auto-sync all_metadata file"

        git push

